import crypto from 'node:crypto';

const ORIGIN='https://info.aec.edu.in', BASE=`${ORIGIN}/acet/`;
const LOGIN=`${BASE}default.aspx`, ATT=`${BASE}Academics/StudentAttendance.aspx?scrid=3&showtype=SA`, PROFILE=`${BASE}Academics/StudentProfile.aspx?scrid=17`;
const KEY='8701661282118308';

const dec=(s='')=>String(s).replace(/&nbsp;/gi,' ').replace(/&amp;/gi,'&').replace(/&quot;/gi,'"').replace(/&#39;/gi,"'").replace(/&lt;/gi,'<').replace(/&gt;/gi,'>');
const text=(s='')=>dec(String(s).replace(/<script\b[\s\S]*?<\/script>/gi,' ').replace(/<style\b[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ')).replace(/\s+/g,' ').trim();
function attr(tag){const o={};for(const m of String(tag).matchAll(/([\w:-]+)\s*=\s*(?:"([^"]*)"|'([^']*)'|([^\s>]+))/g))o[m[1].toLowerCase()]=dec(m[2]??m[3]??m[4]??'');return o}
function setCookies(jar,h){const a=typeof h.getSetCookie==='function'?h.getSetCookie():(h.get('set-cookie')?[h.get('set-cookie')]:[]);for(const raw of a){const p=String(raw).split(';',1)[0],i=p.indexOf('=');if(i>0){const k=p.slice(0,i).trim(),v=p.slice(i+1).trim();if(v)jar.set(k,v);else jar.delete(k)}}}
const cookie=(jar)=>[...jar].map(([k,v])=>`${k}=${v}`).join('; ');
async function req(url,jar,opt={}){let u=new URL(url),method=opt.method||'GET',body=opt.body;for(let i=0;i<9;i++){const h={Accept:'text/html,application/xhtml+xml,*/*;q=0.8','Accept-Language':'en-US,en;q=0.9','User-Agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/152 Safari/537.36',...(opt.headers||{})};const c=cookie(jar);if(c)h.Cookie=c;const r=await fetch(u,{method,body,headers:h,redirect:'manual'});setCookies(jar,r.headers);const loc=r.headers.get('location');if(r.status>=300&&r.status<400&&loc){u=new URL(loc,u);if([301,302,303].includes(r.status)&&method!=='GET'){method='GET';body=undefined}continue}return{r,url:u.toString(),body:await r.text()}}throw new Error('Too many E-CAP redirects')}
function hidden(html){const o={};for(const m of String(html).matchAll(/<input\b[^>]*>/gi)){const a=attr(m[0]);if((a.type||'').toLowerCase()==='hidden'&&a.name)o[a.name]=a.value||''}return o}
function encPass(p){const k=Buffer.from(KEY),c=crypto.createCipheriv('aes-128-cbc',k,k);return Buffer.concat([c.update(String(p),'utf8'),c.final()]).toString('base64')}
const loginPage=(html,url)=>/default\.aspx/i.test(url)&&/\btxtId2\b/i.test(html)&&/\btxtPwd2\b/i.test(html);
async function login(roll,password){const jar=new Map(),first=await req(LOGIN,jar);if(!/\btxtId2\b/i.test(first.body))throw Object.assign(new Error('Could not open E-CAP login form.'),{status:502});const e=encPass(password),f=new URLSearchParams(hidden(first.body));for(const [k,v] of Object.entries({txtId1:'',txtPwd1:'',txtId2:roll,txtPwd2:e,txtId3:'',txtPwd3:'',TextBox1:'',hdnpwd1:'',hdnpwd2:e,hdnpwd3:'','imgBtn2.x':'48','imgBtn2.y':'20'}))f.set(k,v);const out=await req(LOGIN,jar,{method:'POST',body:f.toString(),headers:{'Content-Type':'application/x-www-form-urlencoded',Origin:ORIGIN,Referer:first.url}});if(loginPage(out.body,out.url))throw Object.assign(new Error('E-CAP did not accept this Hall Ticket/password.'),{status:401});return{jar,logged:out}}

function rows(html){const out=[];for(const tr of String(html).matchAll(/<tr\b[^>]*>([\s\S]*?)<\/tr>/gi)){const c=[...tr[1].matchAll(/<t[dh]\b[^>]*>([\s\S]*?)<\/t[dh]>/gi)].map(x=>text(x[1]));if(c.length)out.push(c)}return out}
function n(v){const s=String(v??'').replace(/,/g,'').replace(/%/g,'').trim();if(!s||!/^-?(?:\d+(?:\.\d+)?|\.\d+)$/.test(s))return null;const x=Number(s);return Number.isFinite(x)?x:null}
const ok=(h,a,p)=>h!==null&&a!==null&&p!==null&&h>=0&&a>=0&&a<=h&&p>=0&&p<=100;
function attendance(html){const rs=rows(html),items=[];let total=null;for(let i=0;i<rs.length;i++){const c=rs[i].map(x=>String(x||'').trim());if(/^subject$/i.test(c[0]||'')){const hr=rs.slice(i+1,i+8).find(r=>/^held$/i.test(String(r[0]||'').trim())),ar=rs.slice(i+1,i+9).find(r=>/^attend(?:ed)?$/i.test(String(r[0]||'').trim())),pr=rs.slice(i+1,i+10).find(r=>/^%$|^percentage$/i.test(String(r[0]||'').trim()));if(hr&&ar&&pr){for(let j=1;j<c.length;j++){const sub=c[j],h=n(hr[j]),a=n(ar[j]),p=n(pr[j]);if(/^total$/i.test(sub||'')){if(ok(h,a,p))total={held:h,attended:a,percentage:p}}else if(sub&&ok(h,a,p))items.push({subject:sub,held:h,attended:a,percentage:p})}if(items.length)break}}if(/^total\s*:?$/i.test(c[0]||'')){const z=c.map(n).filter(x=>x!==null);if(z.length>=3){const[h,a,p]=z.slice(-3);if(ok(h,a,p))total={held:h,attended:a,percentage:p}}continue}if(/^\d+$/.test(c[0]||'')&&c.length>=5){const sub=c[1],h=n(c[2]),a=n(c[3]),p=n(c[4]);if(sub&&ok(h,a,p)&&!items.some(x=>x.subject===sub&&x.held===h&&x.attended===a))items.push({subject:sub,held:h,attended:a,percentage:p})}}
if(!total&&items.length){const h=items.reduce((s,x)=>s+x.held,0),a=items.reduce((s,x)=>s+x.attended,0);total={held:h,attended:a,percentage:h?Number((100*a/h).toFixed(2)):0}}return{items,total}}
const has=(a)=>Boolean(a?.total||a?.items?.length);
function jsUnescape(s){let x=String(s||'').trim();if((x.startsWith("'")&&x.endsWith("'"))||(x.startsWith('"')&&x.endsWith('"')))x=x.slice(1,-1);return x.replace(/\\r\\n/g,'\n').replace(/\\n/g,'\n').replace(/\\'/g,"'").replace(/\\"/g,'"').replace(/\\\//g,'/').replace(/\\\\/g,'\\')}
function fromResponse(raw){const cand=[String(raw||''),dec(String(raw||'')),jsUnescape(raw)];try{const j=JSON.parse(raw),stack=[j];while(stack.length&&cand.length<80){const v=stack.pop();if(typeof v==='string')cand.push(v,jsUnescape(v));else if(Array.isArray(v))stack.push(...v);else if(v&&typeof v==='object')stack.push(...Object.values(v))}}catch{}for(const x of cand){const a=attendance(x);if(has(a))return a}return{items:[],total:null}}

function controls(html){const out=[];for(const m of String(html).matchAll(/<(select|input)\b[^>]*>([\s\S]*?<\/select>)?/gi)){const tag=m[0].match(/<(?:select|input)\b[^>]*>/i)?.[0]||m[0],a=attr(tag);if(!a.name&&!a.id)continue;let value=a.value??'';if(/^<select/i.test(m[0])){const os=[...m[0].matchAll(/<option\b[^>]*>([\s\S]*?)<\/option>/gi)].map(o=>{const q=attr(o[0].match(/<option\b[^>]*>/i)?.[0]||'');return{value:q.value??text(o[1]),sel:/\sselected(?:\s|=|>)/i.test(o[0])}});value=(os.find(x=>x.sel)||os.find(x=>x.value!=='')||os[0]||{}).value??''}out.push({name:a.name||'',id:a.id||'',value,type:(a.type||'').toLowerCase(),checked:/\schecked(?:\s|=|>)/i.test(tag)})}return out}
function val(cs,re){const c=cs.find(x=>re.test(`${x.name} ${x.id}`));return c?.value??null}
function values(cs,roll){return{roll,year:val(cs,/(ddlyear|year|acad)/i)||'',from:val(cs,/(fromdate|startdate)/i)||'',to:val(cs,/(todate|enddate)/i)||'',type:val(cs,/(hdntype|showtype|mode|type)/i)||'SA',exclude:cs.find(x=>/(exclude|chkexclude)/i.test(`${x.name} ${x.id}`))?.checked?'true':'false'}}
function scriptUrls(html,base,className){const out=new Set();for(const m of String(html).matchAll(/<script\b[^>]*>/gi)){const a=attr(m[0]);if(!a.src)continue;try{const u=new URL(a.src,base);if(u.origin===ORIGIN&&(/\/ajax\/.*\.ashx/i.test(u.pathname)||new RegExp(className,'i').test(u.pathname)))out.add(u.toString())}catch{}}for(const m of String(html).matchAll(/["']([^"']*\/ajax\/[^"']+\.ashx(?:\?[^"']*)?)["']/gi)){try{const u=new URL(dec(m[1]),base);if(u.origin===ORIGIN&&new RegExp(className,'i').test(u.pathname))out.add(u.toString())}catch{}}return[...out]}
const safe=(s)=>Boolean(s)&&!/(save|update|delete|insert|remove|add|edit|pay|fee|receipt|transaction|password|logout|change|upload|submit)/i.test(s)&&!/^(url|constructor|tostring|valueof)$/i.test(s);
function proxyMethods(js){const s=String(js||''),out=[];const re=/([A-Za-z_$][\w$]*)\s*:\s*function\s*\(([^)]*)\)\s*\{([\s\S]*?)(?=,\s*[A-Za-z_$][\w$]*\s*:\s*function|,\s*url\s*:|\}\s*;?)/g;for(const m of s.matchAll(re)){const name=m[1];if(!safe(name))continue;const body=m[3],q=body.match(/[?&]_method=([A-Za-z_$][\w$]*)[&]_session=([A-Za-z]+)/i);const method=q?.[1]||name;if(!safe(method))continue;const params=m[2].split(',').map(x=>x.trim()).filter(x=>x&&!/^(callback|context|onSuccess|onFailure|onError)$/i.test(x));const payload=[];for(const p of body.matchAll(/([A-Za-z_$][\w$]*)=['"]\s*\+\s*(?:enc|encodeURIComponent)\(\s*([A-Za-z_$][\w$]*)\s*\)/g))payload.push({key:p[1],variable:p[2]});if(!payload.length)for(const p of params)payload.push({key:p,variable:p});out.push({method,session:q?.[2]||'r',payload})}return out}
function map(k,v,x){const s=`${k} ${v}`.toLowerCase();if(/(roll|regno|hall|htno|studentno|userid)/i.test(s))return x.roll;if(/(year|acad|acyear)/i.test(s))return x.year;if(/(fromdate|startdate)/i.test(s))return x.from;if(/(todate|enddate)/i.test(s))return x.to;if(/(exclude|chk)/i.test(s))return x.exclude;if(/(showtype|hdntype|mode|type)/i.test(s))return x.type;if(/scrid/i.test(s))return'3';return''}
async function legacyCall(url,m,x,jar,ref,encoded=true){const u=new URL(url);u.search='';u.searchParams.set('_method',m.method);u.searchParams.set('_session',m.session||'r');const body=m.payload.map(p=>`${p.key}=${encoded?encodeURIComponent(map(p.key,p.variable,x)):map(p.key,p.variable,x)}`).join('\r\n');return req(u,jar,{method:'POST',body,headers:{Accept:'*/*','Content-Type':'text/plain; charset=UTF-8','X-Requested-With':'XMLHttpRequest',Origin:ORIGIN,Referer:ref}})}
async function dynamic(page,jar,roll,className){const cs=controls(page.body),x=values(cs,roll),urls=scriptUrls(page.body,page.url,className),diag={className,scripts:[],methods:[],attempts:[]},methods=[];for(const u of urls){try{const r=await req(u,jar,{headers:{Accept:'application/javascript,text/javascript,*/*;q=0.8',Referer:page.url}});if(r.r.ok){const mm=proxyMethods(r.body);diag.scripts.push({path:new URL(u).pathname,size:r.body.length,count:mm.length});for(const m of mm)methods.push({...m,url:u})}}catch{diag.scripts.push({path:new URL(u).pathname,error:'fetch_failed'})}}const uniq=[];for(const m of methods){const k=`${m.url}|${m.method}|${m.payload.map(p=>p.key).join(',')}`;if(!uniq.some(z=>z.k===k))uniq.push({...m,k})}uniq.sort((a,b)=>(/attend|present|report|get|load|show|data|detail/i.test(a.method)?0:1)-(/attend|present|report|get|load|show|data|detail/i.test(b.method)?0:1));diag.methods=uniq.slice(0,20).map(m=>({name:m.method,session:m.session,params:m.payload.map(p=>p.key)}));for(const m of uniq.slice(0,12)){for(const encoded of [true,false]){try{const r=await legacyCall(m.url,m,x,jar,page.url,encoded),a=fromResponse(r.body);diag.attempts.push({method:m.method,encoded,status:r.r.status,size:r.body.length,found:has(a)});if(has(a))return{attendance:a,source:`${className}.${m.method}`,diag}}catch{diag.attempts.push({method:m.method,encoded,result:'request_error'})}}}return{attendance:{items:[],total:null},source:null,diag}}
async function postback(page,jar){const f=new URLSearchParams(hidden(page.body));for(const c of controls(page.body))if(c.name&&!['button','submit','image'].includes(c.type))f.set(c.name,c.value||'');f.set('__EVENTTARGET','');f.set('__EVENTARGUMENT','');f.set('btnShow','Show');f.set('ctl00$CapPlaceHolder$btnShow','Show');try{const r=await req(ATT,jar,{method:'POST',body:f.toString(),headers:{'Content-Type':'application/x-www-form-urlencoded',Origin:ORIGIN,Referer:page.url}});return fromResponse(r.body)}catch{return{items:[],total:null}}}
function profile(html,roll){const rs=rows(html);const get=(names)=>{for(const r of rs)for(let i=0;i<r.length;i++)if(names.includes(String(r[i]||'').replace(/\s*:\s*$/,'').trim().toLowerCase()))for(const z of r.slice(i+1))if(z&&z!==':')return z;return''};return{rollNo:get(['rollno','roll no','hall ticket no'])||roll,name:get(['name','student name']),course:get(['course']),branch:get(['branch']),semester:get(['semester','sem'])}}

export default async function handler(request,res){res.setHeader('Cache-Control','no-store');if(request.method!=='POST')return res.status(405).json({error:'Method not allowed'});const roll=String(request.body?.rollNo||'').trim().toUpperCase(),password=String(request.body?.password||'');if(!/^[A-Z0-9]{6,20}$/.test(roll)||!password||password.length>128)return res.status(400).json({error:'Enter a valid roll number and E-CAP password'});try{const{jar,logged}=await login(roll,password),page=await req(ATT,jar,{headers:{Referer:logged.url}});if(!page.r.ok||loginPage(page.body,page.url))return res.status(401).json({error:'E-CAP session expired before Attendance opened.'});let a=fromResponse(page.body),source=has(a)?'attendance_page':null,attendanceDiag=null,profileDiag=null;if(!has(a)){const d=await dynamic(page,jar,roll,'StudentAttendance');attendanceDiag=d.diag;if(has(d.attendance)){a=d.attendance;source=d.source}}if(!has(a)){const p=await postback(page,jar);if(has(p)){a=p;source='attendance_postback'}}let meta={rollNo:roll};try{const pp=await req(PROFILE,jar,{headers:{Referer:page.url}});meta=profile(pp.body,roll);if(!has(a)){const pa=fromResponse(pp.body);if(has(pa)){a=pa;source='profile_page'}else{const d=await dynamic(pp,jar,roll,'StudentProfile');profileDiag=d.diag;if(has(d.attendance)){a=d.attendance;source=d.source}}}}catch{}if(meta.rollNo&&meta.rollNo.toUpperCase()!==roll)return res.status(403).json({error:'E-CAP account does not match your Student 360 roll number.'});console.info('E-CAP attendance v7',JSON.stringify({source:source||'none',subjectCount:a.items.length,total:Boolean(a.total),attendanceDiag,profileDiag}));if(!has(a))return res.status(422).json({error:'E-CAP login succeeded, but the live attendance response could not be decoded yet.',stage:'attendance_dynamic',reason:'legacy_ajax_mapping_pending_v7'});return res.status(200).json({success:true,source:'ACET E-CAP',attendance:a,profile:meta,syncedAt:new Date().toISOString()})}catch(e){console.error('E-CAP attendance v7 failed',{message:e?.message||String(e)});return res.status(Number(e?.status)||502).json({error:e?.message||'Unable to sync attendance from ACET E-CAP.'})}}
